
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getAppMode() : Promise<AppMode> {
    return await TAURI_INVOKE("get_app_mode");
},
async getGitStatus(path: string) : Promise<Result<GitStatus, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_git_status", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFileDiff(repoPath: string, filePath: string, target: DiffTarget) : Promise<Result<FileDiff, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_diff", { repoPath, filePath, target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGitFileContents(repoPath: string, filePath: string, target: DiffTarget) : Promise<Result<GitFileContents, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_git_file_contents", { repoPath, filePath, target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readFile(filePath: string) : Promise<Result<ReadFileResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppMode = { type: "empty" } | { type: "git"; path: string } | { type: "file"; fileA: string; fileB: string }
/**
 * Serializable error type for Tauri commands.
 * Converts AppError variants to a format that can cross the IPC boundary.
 */
export type CommandError = { type: "path"; path: string; message: string } | { type: "utf8"; path: string } | { type: "git"; path: string; message: string }
/**
 * A file version for diff rendering
 */
export type DiffFile = { name: string; lang: string | null; 
/**
 * None = file doesn't exist in this version
 */
content: FileContent | null }
/**
 * A hunk (section) of a diff
 */
export type DiffHunk = { oldStart: number; oldLines: number; newStart: number; newLines: number; header: string; lines: DiffLine[] }
/**
 * A single line in a diff
 */
export type DiffLine = { changeType: LineChangeType; content: string; oldLineNo: number | null; newLineNo: number | null }
/**
 * Whether to get staged or unstaged changes
 */
export type DiffTarget = "staged" | "unstaged"
/**
 * Content of a file - either readable text or opaque binary
 */
export type FileContent = { type: "text"; contents: string } | { type: "binary"; size: number }
/**
 * Complete diff for a single file
 */
export type FileDiff = { path: string; oldPath: string | null; hunks: DiffHunk[]; isBinary: boolean }
export type FileEntry = { path: string; status: FileStatus; oldPath: string | null }
export type FileStatus = "added" | "modified" | "deleted" | "renamed" | "untracked" | "typechange" | "conflicted"
/**
 * Result of getting file contents for diff
 */
export type GitFileContents = { oldFile: DiffFile; newFile: DiffFile }
export type GitStatus = { staged: FileEntry[]; unstaged: FileEntry[]; untracked: FileEntry[] }
/**
 * Type of change for a diff line
 */
export type LineChangeType = "context" | "addition" | "deletion"
/**
 * Result of reading a file from the filesystem
 */
export type ReadFileResult = { name: string; contents: string; lang: string | null; isBinary: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
