
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getAppMode() : Promise<AppMode> {
    return await TAURI_INVOKE("get_app_mode");
},
async getGitStatus(path: string) : Promise<Result<GitStatus, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_git_status", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFileDiff(repoPath: string, filePath: string, target: DiffTarget) : Promise<Result<FileDiff, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_diff", { repoPath, filePath, target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGitFileContents(repoPath: string, filePath: string, target: DiffTarget) : Promise<Result<GitFileContents, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_git_file_contents", { repoPath, filePath, target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readFile(filePath: string) : Promise<Result<ReadFileResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadComments(repoPath: string) : Promise<Result<CommentCollection, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_comments", { repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveComment(repoPath: string, comment: Comment, fileContents: string | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_comment", { repoPath, comment, fileContents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteComment(repoPath: string, commentId: string) : Promise<Result<boolean, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_comment", { repoPath, commentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCommentsForFile(repoPath: string, filePath: string, fileContents: string) : Promise<Result<Comment[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_comments_for_file", { repoPath, filePath, fileContents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppMode = { type: "empty" } | { type: "git"; path: string } | { type: "file"; fileA: string; fileB: string }
export type CommandError = { type: "path"; path: string; message: string } | { type: "utf8"; path: string } | { type: "git"; path: string; message: string }
export type Comment = { id: string; filePath: string; anchor: CommentAnchor; body: string; resolved: boolean; createdAt: number; updatedAt: number }
export type CommentAnchor = { type: "pinned"; line: number } | { type: "tracked"; line: number; context: string } | { type: "orphaned"; last_known_line: number; context: string }
export type CommentCollection = { comments: Comment[] }
export type DiffContent = { contentType: "text"; hunks: DiffHunk[] } | { contentType: "binary" }
export type DiffFile = { name: string; lang: string | null; content: FileContent | null }
export type DiffHunk = { oldStart: number; oldLines: number; newStart: number; newLines: number; header: string; lines: DiffLine[] }
export type DiffLine = { changeType: LineChangeType; content: string; oldLineNo: number | null; newLineNo: number | null }
export type DiffTarget = "staged" | "unstaged"
export type FileContent = { type: "text"; contents: string } | { type: "binary"; size: number }
export type FileDiff = { path: string; oldPath: string | null; content: DiffContent }
export type FileEntry = { path: string; kind: FileEntryKind }
export type FileEntryKind = { status: "added" } | { status: "modified" } | { status: "deleted" } | { status: "renamed"; old_path: string } | { status: "untracked" } | { status: "typechange" } | { status: "conflicted" }
export type GitFileContents = { oldFile: DiffFile; newFile: DiffFile }
export type GitStatus = { staged: FileEntry[]; unstaged: FileEntry[]; untracked: FileEntry[] }
export type LineChangeType = "context" | "addition" | "deletion"
export type ReadFileResult = { name: string; contents: string; lang: string | null; isBinary: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
